/**
 * 
 */
package com.cwt.kafka.consumer.entity;

import org.springframework.stereotype.Component;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@Component
public class Employee1 {

	public String employeeid;

	public String firstName;
	
	public int salary;
	
	public boolean maritalStatus;

	public Employee1() {
	}

	public Employee1(String firstName, int salary, boolean maritalStatus) {
		this.employeeid=employeeid;
		this.firstName = firstName;
		this.salary = salary;
		this.maritalStatus = maritalStatus;
	}


	public String getEmployeeid() {
		return employeeid;
	}

	public void setEmployeeid(String employeeid) {
		this.employeeid = employeeid;
	}

	public String getFirstName() {
		return firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public int getSalary() {
		return salary;
	}

	public void setSalary(int salary) {
		this.salary = salary;
	}

	public boolean isMaritalStatus() {
		return maritalStatus;
	}

	public void setMaritalStatus(boolean maritalStatus) {
		this.maritalStatus = maritalStatus;
	}

	@Override
	public String toString() {
		return "Employee1 [employeeid=" + employeeid + ", firstName=" + firstName + ", salary=" + salary
				+ ", maritalStatus=" + maritalStatus + "]";
	}

	
	
}